name: brainnotation_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8
  - boto3
  - botocore
  - flake8
  - ipython
  - matplotlib
  - nibabel
  - nilearn
  - numba
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - pip:
    - mayavi
    - pysurfer
    - nimare
    - git+https://github.com/netneurolab/netneurotools.git
    - -e brainnotation
    - -e brainnotation_dev
